<Project>
    <PropertyGroup>
        <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup Label="Pins">
    </ItemGroup>
    <ItemGroup Label="Main">
    </ItemGroup>
    <ItemGroup Label="Test">
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageVersion Include="xunit.v3" Version="4.0.0"/>
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0"/>
    </ItemGroup>
</Project>