<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PerformantReflection\PerformantReflection.csproj"/>
    </ItemGroup>

</Project>
